### ISSUE TITLE
aquestion

### ISSUE THREAD

**Issue by lsy1130** [hahashu/TextileNet#1]
hello.
I have aquestion.
1. What are the classification criteria for textiles and fabrics?
2. What are the criteria for 33 fibre labels and 27 fabric labels?

**Comment by hahashu** [comment]
> hello. I have aquestion.
> 
> 1. What are the classification criteria for textiles and fabrics?
> 2. What are the criteria for 33 fibre labels and 27 fabric labels?

Hi,

Thanks for your questions.

1. I guess you mean fibre and fabric, generally, both fibre and fabric are subsets of textiles, and this is also a main reason we built this dataset. You can build image classification models for either subsets and the classification metrics here can be top1, top3 and top5 accuracy.

2. Good question! I will update a file that contains a mapping between class ids and label names (how each id is associated what types of fibre/fabric) today.

Many thanks!
